export default function getHeadingWarning(version: string): string {
    return `
/**|===vscode-flutter-sqlite-extension===|
 * |        version ${version}` + " ".repeat(21 - version.length) + `|
 * |This file is automatically generated | 
 * |vscode-flutter-sqlite-extension      |
 * |Do not manually edit or delete       |
 * |=====================================|
*/

/// The content is generated by vscode-flutter-sqlite-extension`;
}