import getHeadingWarning from "../heading_warning";

export default function getConcreteUserAccountContent(
  version: string,
  packageName: string, ): string {
  var headingWarning = getHeadingWarning(version);

  return `${headingWarning}

/// The following imports are generated by vscode-flutter-sqlite-extension
import 'package:${packageName}/helpers/database/database_annotations.dart';
import 'package:${packageName}/helpers/database/db_entity.dart';
/// end of generated imports vscode-flutter-sqlite-extension

@DataTable("profile_contacts")
class UserAccount implements DbAccountEntity {

  @DataColumn("id", ColumnMetadata.PrimaryKey & ColumnMetadata.Unique & ColumnMetadata.AutoIncrement)
  int _id;

  @DataColumn("account_name", ColumnMetadata.NotNull)
  String _accountName;

  @DataColumn("account_email", ColumnMetadata.NotNull)
  String _accountEmail;

  @DataColumn("account_abbr", ColumnMetadata.NotNull)
  String _accountAbbr;  

  UserAccount(this._accountName, this._accountEmail, this._accountAbbr);

  @override
  UserAccount.empty() {
    _accountName = "";
    _accountEmail = "";
    _accountAbbr = "";
  }

  @override
  UserAccount.map(dynamic obj) {
    this._id = obj['id'];
    this._accountName = obj['account_name'];
    this._accountEmail = obj['account_email'];
    this._accountAbbr = obj['account_abbr'];
  }

  @override
  UserAccount.fromMap(Map<String, dynamic> map) {
    this._id = map['id'];
    this._accountName = map['account_name'];
    this._accountEmail = map['account_email'];
    this._accountAbbr = map['account_abbr'];
  }

  @override
  int get id => _id;

  String get accountName => _accountName;
  String get accountEmail => _accountEmail;
  String get accountAbbr => _accountAbbr;

  @override
  Map<String, dynamic> toMap() {
    var map = new Map<String, dynamic>();
    if (_id != null) {
      map['id'] = _id;
    }
    map['account_name'] = _accountName;
    map['account_email'] = _accountEmail;
    map['account_abbr'] = _accountAbbr;

    return map;
  }
}
`;
}