import getHeadingWarning from "../heading_warning";
import { Utils } from "../../utils/utils";

interface IPropertyType {
  columnName: string;
  columnType: string;
}

/**
 * Generates the content for the /models/your_model.dart file
 * Returns a string with the content
*/
export default function getConcreteIndependentEntitySkeletonContent(
  version: string,
  packageName: string,
  entityNameInPascalCase: string,
  propertiesList: { [id: string]: IPropertyType } = {}
): string {
  var headingWarning = getHeadingWarning(version);
  var entityNameInUnderscoreCase = Utils.getUnderscoreCasePlural(entityNameInPascalCase);

  return `${headingWarning}

/// The following imports are generated by vscode-flutter-sqlite-extension
import 'package:flutter_orm_m8/flutter_orm_m8.dart';
import 'package:${packageName}/helpers/database/db_entity.dart';
/// end of generated imports vscode-flutter-sqlite-extension

@DataTable("${entityNameInUnderscoreCase}")
class ${entityNameInPascalCase} implements DbEntity {
  @DataColumn("id", ColumnMetadata.PrimaryKey & ColumnMetadata.Unique & ColumnMetadata.AutoIncrement)
  int _id;

  @DataColumn("record_date")
  int _recordDate;

  @DataColumn("is_deleted")
  int _isDeleted;

  /*String _entryName;*/
  
  ${entityNameInPascalCase}(this._recordDate, /*this._entryName*/);

  ${entityNameInPascalCase}.empty() {
    /*_entryName = "";*/
  }

  void setId(int newId) {
    _id = newId;
  }

  ${entityNameInPascalCase}.map(dynamic obj) {
    this._id = obj['id'];
    this._recordDate = obj['record_date'];
    this._isDeleted = obj['is_deleted'];

    /*this._entryName = obj['entry_name'];*/
  }

  ${entityNameInPascalCase}.fromMap(Map<String, dynamic> map) {
    this._id = map['id'];
    this._recordDate = map['record_date'];
    this._isDeleted = map['isDeleted'];

    /*this._entryName = map['entry_name'];*/
  }

  int get id => _id;
  int get recordDate => _recordDate;
  int get isDeleted => _isDeleted;

  /*String get entryName => _entryName;*/

  Map<String, dynamic> toMap() {
    var map = new Map<String, dynamic>();
    if (_id != null) {
      map['id'] = _id;
    }
    map['record_date'] = _recordDate;
    map['is_deleted'] = _isDeleted;

    /*map['entry_name'] = _entryName;*/
    return map;
  }
}
`;
}