class Utils {
  static getEntityNamePluralsInPascalCase(entityNameInPascalCase: string): any {
    throw new Error("Method not implemented.");
  }
  static getEntityNameInCamelCase(entityNameInPascalCase: string): any {
    throw new Error("Method not implemented.");
  }
  static getUnderscoreCase(entityNameInPascalCase: string): any {
    throw new Error("Method not implemented.");
  }
  static getHeadingWarning(): string {
    return `
    /**
     * This file is automatically generated by 
     * vscode-flutter-sqlite-extension
     * Do not manually edit or delete
    */`;
  }
}